<?php
/**
 * Created by PhpStorm.
 * User: JMaratier
 * Date: 05/11/2018
 * Time: 10:06
 */

use yii\db\Migration;

class m160408_074834_insert_analyse_germe extends Migration
{
    public function up()
    {
        $this->batchInsert('analyse_germe',['id', 'id_service','libelle','code'],[
            [1, 1, 'Aspergillus brasiliensis','Asp. brasi.'],
            [2, 1, 'Aspergillus niger','ASPN'],
            [3, 1, 'Bactéries aérobies mésophiles','BACT'],
            [4, 1, 'Candida albicans','CA'],
            [5, 1, 'Escherichia coli','EC'],
            [6, 1, 'Flore totale','FT01'],
            [7, 1, 'Germes non spécifiés','GNS'],
            [8, 1, 'Germes spécifiés','GS'],
            [9, 1, 'Germes totaux','GTTM103'],
            [10, 1, 'Germes totaux','GTOREAL'],
            [11, 1, 'Germes totaux Procter et Gamble','GTPG'],
            [12, 1, 'Identification microbienne','ID'],
            [13, 1, 'Levures-moisissures','LM'],
            [15, 1, 'Levures-moisissures','LMTM103'],
            [16, 1, 'Levures-moisissures à 20-25°C','LMOREAL'],
            [17, 1, 'Levures moisissures Procter et Gamble','LMPG'],
            [18, 1, 'Moisissures','Mois'],
            [19, 1, 'Pseudomonas aeruginosa','PS'],
            [20, 1, 'Staphylococcus aureus','STA'],
            [21, 2, 'Bactéries lactiques mésophiles','FL01'],
            [22, 2, 'Coliformes (UFC)','CTEAU'],
            [23, 2, 'Coliformes thermotolérants','CFEAU'],
            [24, 2, 'Dont Legionella pneumophila','LEGPN'],
            [25, 2, 'Entérocoques intestinaux (UFC)','STREAU'],
            [26, 2, 'Escherichia coli (UFC)','ECEAU'],
            [27, 2, 'Legionella (confirmation du genre)','LEGIO'],
            [28, 2, 'Legionella Pneumophila (identification de l\'espèce)','L_PNEUMO'],
            [29, 2, 'Legionella spp','LEGSPP'],
            [30, 2, 'Legionelle','LEG'],
            [31, 2, 'Levures-moisissures','LMOGA'],
            [32, 2, 'Listeria monocytogenes','LIST'],
            [33, 2, 'Listeria spp','LSPP'],
            [34, 2, 'Micro-organismes aérobies revivifiables à 22°C (UFC)','GTEAU22'],
            [35, 2, 'Micro-organismes aérobies revivifiables à 30°C','GT30'],
            [36, 2, 'Micro-organismes aérobies revivifiables à 36°C (UFC)','GTEAU37'],
            [37, 2, 'Micro-organismes totaux à 30-35°C','GT30-35'],
            [38, 2, 'Pseudomonas aeruginosa (UFC)','PSEAU'],
            [39, 2, 'Pseudomonas spp','PSSPP'],
            [40, 2, 'Salmonella','SALMEAU'],
            [41, 2, 'Sérogroupe Legionella pneumophila','IDLP'],
            [42, 2, 'Spore thermorésistantes mésophiles','SPORETH'],
            [43, 2, 'Spores de micro-organismes anaérobies sulfito-réducteurs (UFC)','ASREAU'],
            [44, 2, 'Staphylococcus à coagulase positive (UFC)','STAEAU'],
            [45, 3, 'Bacillus cereus présomptif à 30°C','BCP'],
            [46, 3, 'Bactéries lactiques mésophiles','BLM'],
            [47, 3, 'Bactéries mésophiles aérobies (forme végétative)','BMA'],
            [48, 3, 'Bactéries mésophiles anaérobies (forme végétative)','BMAna'],
            [49, 3, 'Bactéries sulfito-réductrices à 37°c','ASR37'],
            [50, 3, 'Bactéries sulfito-réductrices à 46°C','ASR'],
            [51, 3, 'Campylobacter','CAMPY'],
            [52, 3, 'Clostridium perfringens','CLOS'],
            [53, 3, 'Coliformes (méthode JETRO)','C(JETRO)'],
            [54, 3, 'Coliformes à 30°C','CT'],
            [55, 3, 'Coliformes présumés à 30°C','CT'],
            [56, 3, 'Coliformes présumés à 37°C','CT37'],
            [57, 3, 'Coliformes thermotolérants','CF'],
            [58, 3, 'Confirmation microbienne','CM'],
            [59, 3, 'Entérobactéries','ENT'],
            [60, 3, 'Enterobacteries à 37°c','ENT37ISO'],
            [61, 3, 'Entérobactéries présumées à 30°C','ENT'],
            [62, 3, 'Enterobactéries présumées à 37°C','ENT37'],
            [63, 3, 'Enterococcus faecalis','ENTFAC'],
            [64, 3, 'Enterococcus faecium','ENTFA'],
            [65, 3, 'Entérocoques','STR'],
            [66, 3, 'Escherichia coli B-glucuronidase positive','EC'],
            [67, 3, 'Escherichia coli O157 incluant H7','ECO157'],
            [68, 3, 'Levures','LEV'],
            [69, 3, 'Levures et moisissures','LM'],
            [70, 3, 'Levures et moisissures sur milieu à faible aw','LMAW'],
            [71, 3, 'Levures sur milieu à faible aw','LAW'],
            [72, 3, 'Listeria monocytogenes','LIST'],
            [73, 3, 'Listeria spp','LSPP'],
            [74, 3, 'Listeria spp (sauf L monocytogenes)','LIST SPP'],
            [75, 3, 'Micro-organismes à 25°C','GT25'],
            [76, 3, 'Micro-organismes à 30°C','GT30'],
            [77, 3, 'Micro-organismes à 30°C anaérobies','GTANA30'],
            [78, 3, 'Micro-organismes à 30°C incubés 48h','GT30S'],
            [79, 3, 'Micro-organismes à 37°C','GT37'],
            [80, 3, 'Micro-organismes psychrotrophes','GTSPYCHR'],
            [81, 3, 'Microorganismes aérobies à 30°C + cycloheximide','GT30CYCLO'],
            [82, 3, 'Moisissures','MS'],
            [83, 3, 'Moisissures sur milieu à faible aw','MAW'],
            [84, 3, 'Pseudomonas aeruginosa','PSAERU'],
            [85, 3, 'Pseudomonas spp présomptifs','PS'],
            [87, 3, 'Ratio micro-organismes à 30°C / bactéries lactiques','Ratio'],
            [88, 3, 'Ratio micro-organismes à 30°C incubés à 48h/ bactéries lactiques','Ratio'],
            [89, 3, 'Salmonella','SALM'],
            [90, 3, 'Salmonella (sauf Typhi et Paratyphi)','SALM'],
            [91, 3, 'Sérogroupes O26, O45, O103, O111, O121, O145 et O157','SRG STEC'],
            [92, 3, 'Spores de Bacillus cereus présomptif à 30°C','SPBC'],
            [93, 3, 'Spores de Bacillus et Clostridium à 30°C','SPO02'],
            [94, 3, 'Spores de Bacillus et Clostridium à 55°C','SPO03'],
            [95, 3, 'Spores de bactéries anaérobies à 30°C','SPO07'],
            [96, 3, 'Spores de bactéries sulfito-réductrices à 37°C','SPASR37'],
            [97, 3, 'Spores de bactéries sulfito-réductrices à 46°C','SPASR46'],
            [98, 3, 'Spores thermorésistantes aérobies mésophiles','SPAM'],
            [99, 3, 'Spores thermorésistantes aérobies thermophiles','SPAT'],
            [100, 3, 'Spores thermorésistantes anaérobies mésophiles','SPANAM'],
            [101, 3, 'Spores thermorésistantes anaérobies thermophiles','SPANAT'],
            [102, 3, 'Spores thermorésistantes mésophiles','SPO01'],
            [103, 3, 'Staphylococcus à coagulase positive à 37°C','STA'],
            [104, 3, 'Streptococcus B hémolytique','STRB'],
            [105, 3, 'Streptococcus thermophilus','STRTH'],
            [106, 3, 'Streptococcus zooepidemicus','STRZOO'],
            [107, 3, 'Streptocoques fécaux','STR'],
            [108, 4, 'Bactéries','BACT'],
            [109, 4, 'Bactéries Gram négatives résistantes aux sels biliaires','ENTPE'],
            [110, 4, 'Candida albicans','CA'],
            [111, 4, 'Champignons','CH'],
            [112, 4, 'Charge microbienne totale','CMT'],
            [113, 4, 'Dénombrement microbien','DM'],
            [114, 4, 'Escherichia coli','ECPE'],
            [115, 4, 'Germes aérobies totaux','DGAT'],
            [116, 4, 'Germes aérobies totaux 34-38°c','GT'],
            [117, 4, 'Germes aérobies totaux 40,5-42,5°c','GT'],
            [118, 4, 'Germes aérobies totaux à 7 jours','DGAT7J'],
            [119, 4, 'Levures','LPE'],
            [120, 4, 'Levures Moisissures totales','DLMT'],
            [121, 4, 'Levures Moisissures totales à 7 jours','DLMT7J'],
            [122, 4, 'Micro-organismes aérobies viables','MAV'],
            [123, 4, 'Moisissures','MPE'],
            [124, 4, 'Pseudomonas aeruginosa','PSPE'],
            [125, 4, 'Salmonella','SALMPE'],
            [126, 4, 'Staphylococcus aureus','STAPE'],
        ]);
    }

    public function down()
    {
        echo "m160411_101559_insert_analyse_germe cannot be reverted.\n";

        return false;
    }
}